### ISSUE TITLE
Change the scripts variable to automatically determine directory where rest of scripts are

### ISSUE THREAD

**Issue by hyphaltip** [srobb1/RelocaTE#1]
Use something like the answers here and the FindBin module to determine the folder the script is running from in order to execute the other scripts.

http://stackoverflow.com/questions/84932/how-do-i-get-the-full-path-to-a-perl-script-that-is-executing

**Comment by srobb1** [comment]
i got it working with FindBin. i commited it already :) yeah!

On Fri, May 18, 2012 at 11:27 AM, Jason Stajich <
reply@reply.github.com

> wrote:
> 
> Use something like the answers here and the FindBin module to determine
> the folder the script is running from in order to execute the other scripts.
> 
> http://stackoverflow.com/questions/84932/how-do-i-get-the-full-path-to-a-perl-script-that-is-executing
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/srobb1/RelocaTE/issues/1

## 

Sofia Robb, Ph.D
Wessler and Stajich Laboratories
University of California Riverside

**Comment by srobb1** [comment]
Fixed it with FindBin
